---
title: "Makuyuni Summary and Validation"
author:
  - "Joseph Holler"
  - "Justin Lucas"
date: "`r Sys.Date()`"
output: html_document
---

# Statistical tests and summary statistics for Makuyuni Wildlife Corridor study

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r load-data}
# read in minimum cost (of least cost corridor)
transect_observations <- read.csv("minimum_cost.csv")

# Read in wildlife and livestock observation data
observation_data <- read_excel("observation_data.xlsx")
```

```{r summarize-obs-by-transect}
# summarize the counts of wild and domestic animals by transect
sum_obs <- observation_data %>% 
  select(Transect, Wild_Dom, Counts) %>% 
  group_by(Transect, Wild_Dom) %>% 
  summarise(totals = sum(Counts), .groups="drop")

# create mammals table with one row per transect, 
# wildlife counts in one column and
# livestock counts in another
livestock <- sum_obs %>% filter(Wild_Dom == "Dom") %>% select(Transect, livestock = totals)
wildlife <- sum_obs %>% filter(Wild_Dom == "Wild") %>% select(Transect, wildlife = totals)

# join wildlife and livestock counts to transect_observations
transect_observations <- transect_observations %>% 
  left_join(wildlife, by="Transect") %>% 
  left_join(livestock, by="Transect")

# remove temporary tables
rm(sum_obs, wildlife, livestock)

transect_observations
```


```{r display-transect-data}
transect_observations
```


What percentage transects contained wildlife?

```{r transects-with-wildlife}
# ratio of transects with wildlife observations
sum(!is.na(transect_observations$wildlife)) / nrow(transect_observations)
```

What percentage transects contained livestock?

```{r transects-with-livestock}
# ratio of transects with livestock observations
sum(!is.na(transect_observations$livestock)) / nrow(transect_observations)
```
```{r replace-na-with-0-and-calculate-ranks}
# fill transects with no (NA) observations with 0
transect_observations$livestock <- replace_na(transect_observations$livestock, 0)
transect_observations$wildlife <- replace_na(transect_observations$wildlife, 0)

# calculate ranks
transect_observations$lsrank <- rank(-transect_observations$livestock)
transect_observations$wirank <- rank(-transect_observations$wildlife)
transect_observations$ranksum <- transect_observations$lsrank + transect_observations$wirank
```


```{r corridor-correlation}
# Spearman's Rho correlation test, one-tailed
# HA: There is a negative correlation between wildlife corridor cost and observation of wildlife
corridor_test <- cor.test(transect_observations$min_corridor_cost, transect_observations$wildlife, method = "spearm", alternative = "less")
corridor_test
```

```{r livestock-correlation}
# Filter for transects with non-zero observations
nonzero_obs <- filter(transect_observations, wildlife > 0 | livestock > 0) 

# spearman's rho correlation test, one-tailed
# HA: There is a negative correlation between number of livestock observed and number of wildlife observed
cor.test(nonzero_obs$livestock, 
         nonzero_obs$wildlife,
         method = "spearm",
         alternative = "less")
```

